name: Radar Veri Motoru

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  veri_cek:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: pip install requests beautifulsoup4

      - name: Scraper Motorunu Çalıştır
        run: python motor.py

      - name: Yeni Oranları Kaydet
        run: |
          git config --global user.name 'RadarBot'
          git config --global user.email 'bot@radar.com'
          git add canli_oranlar.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Veri Güncellendi" && git push)
